name: Cairo tests

on:
  push:
    branches:
      - main
    paths-ignore:
      - "**.md"
  pull_request:
    paths-ignore:
      - "**.md"

# scarb and snfoundry use .tool-versions
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: software-mansion/setup-scarb@v1
      - run: scarb fmt --check
      - run: scarb build

      - uses: foundry-rs/setup-snfoundry@v3
      - run: snforge test
